# Site
name: "Mundana"
description: "Jaewan-Sangji Tech Blog"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl: "/pages"
disqus: "demowebsite"
email: "ianlee9180@gmail.com"
mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
  jaewan:
    name: jaewan
    site: https://www.linkedin.com/in/jaewan-lee-b670bb138
    avatar: /assets/images/jaewan_avatar.jpg
    bio: |
      [ZigBang Backend Developer] <br>
      * Enjoy and challenge all areas of development. <br>
      * Typescript, NodeJS, Java, React, Android
    email: ianlee9180@gmail.com
    twitter: https://twitter.com/wowthemesnet

  sangji:
    name: sangji
    site: https://www.linkedin.com/in/sangji-yoo-13642615b
    avatar: /assets/images/sangji_avatar.jpg
    bio: "KnoLabs Backend Developer,"
    email: fakemail@gmail.com
    twitter: https://twitter.com/wowthemesnet

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: jaewan
      avatar: /assets/images/jaewan_avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  [
    README.markdown,
    package.json,
    grunt.js,
    Gruntfile.js,
    Gruntfile.coffee,
    node_modules,
  ]
